Project Name:
- nightzan999.github.io
Languages:
- html
- css
- scss
Description:
- It is a website for NightZan999
Features:
- Must talk about NightZan999
- Must have bootstrap 4
- Must have W3 CSS
- Uses github domains
- Talks about contact and redirects pages
- Must use custom SASS and styling